macro_rules! def_consts {
    ($($name:ident = $val:expr;)*) => { $( pub const $name: usize = $val;)* };
}

def_consts! {
    N = 256;
    Q = 3329;

    SYMBYTES = 32;
    SSBYTES = 32;

    POLYBYTES = 384;
    POLYVECBYTES = K * POLYBYTES;

    K = 3;
    ETA1 = 2;
    POLYCOMPRESSEDBYTES = 128;
    POLYVECCOMPRESSEDBYTES = K * 320;

    ETA2 = 2;

    INDCPA_MSGBYTES = SYMBYTES;
    INDCPA_PUBLICKEYBYTES = POLYVECBYTES + SYMBYTES;
    INDCPA_SECRETKEYBYTES = POLYVECBYTES;
    INDCPA_BYTES = POLYVECCOMPRESSEDBYTES + POLYCOMPRESSEDBYTES;

    PUBLICKEYBYTES = INDCPA_PUBLICKEYBYTES;
    SECRETKEYBYTES = INDCPA_SECRETKEYBYTES + INDCPA_PUBLICKEYBYTES + 2 * SYMBYTES;
    CIPHERTEXTBYTES = INDCPA_BYTES;
}
