[package]
repository = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
categories = { workspace = true }
keywords = { workspace = true }
name = "falcon"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2021"
autobins = false

[lib]
name = "falcon"
path = "lib.rs"

[dependencies]
rand_core = { version = "0.6.4", default-features = false }
sha3 = { version = "0.10.8", default-features = false }

[lints]
workspace = true
