[package]
repository = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
categories = { workspace = true }
keywords = { workspace = true }
name = "topology-wrapper"
version = "0.1.0"
edition = "2021"
description = "topology visualization protocols for libp2p"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
component-utils = { version = "0.1.0", path = "../component-utils" }
libp2p = "0.53.1"
log = "0.4.20"

[features]
disabled = []

[lints]
workspace = true
