[package]
repository = { workspace = true }
license = { workspace = true }
readme = { workspace = true }
categories = { workspace = true }
keywords = { workspace = true }
name = "kyber"
version = "0.1.0"
edition = "2021"
description = "postquantum secure key encapsulation standard"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha3 = { version = "0.10.8", default-features = false }

[lints]
workspace = true
